/*
 * This source file was generated by the Gradle 'init' task
 */
package newer;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Pantry pantry = new Pantry();
        Cookbook cookbook = new Cookbook("Salty");
        Kitchen kitchen = new Kitchen();

/* 
Ingredient potato = new Ingredient("potato", 500, "grams");
        Ingredient garlic = new Ingredient("garlic", 4, "heads");
        Ingredient milk = new Ingredient("milk", 1, "liter");
        pantry.add(potato);
        pantry.add(garlic);
        pantry.add(milk);

        pantry.add(Ingredient.create());
        pantry.add(Ingredient.create());
        pantry.add(Ingredient.create());

        pantry.show();
*/
        //cookbook.add(Recipe.create());
        //cookbook.show();
      while (true) {
        System.out.println("Welcome to the kitchen app. Press a number for one of the following options. \n 1. Show your pantry \n 2. Add to your pantry \n 3. Remove an item from your pantry \n 4. Show your recipes \n 5. Add a recipe \n 6. Remove recipe \n 7. Compare your pantry and what recipes you can make" );
        Scanner s = new Scanner(System.in);
        int choice = s.nextInt();

        switch (choice) {
            case 1 -> pantry.show();
            case 2 -> pantry.add(Ingredient.create());
            case 3 -> {
            }
            case 4 -> cookbook.show();
            case 5 -> cookbook.add(Recipe.create());
            case 6 -> {
            }
            case 7 -> kitchen.comparePantryAndRecipe(pantry, cookbook);
            default -> System.out.println("Invalid choice. Please select a number from 1 to 7.");
        }
        //pantry.remove(Ingredient.create());
        //cookbook.remove(Recipe.create());
            }
          }
}
