/*
 * This source file was generated by the Gradle 'init' task
 */
package newer.Kitchenapp.Valpha09;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
      Pantry pantry = DataManager.loadPantry();
      Cookbook cookbook = new Cookbook("Salty");
      Kitchen kitchen = new Kitchen();

      while (true) {
        System.out.println("Welcome to the kitchen app. Press a number for one of the following options. \n 1. Show your pantry \n 2. Add to your pantry \n 3. Remove an item from your pantry \n 4. Show your recipes \n 5. Read a recipe \n 6. Add a recipe \n 7. Remove recipe \n 8. Compare your pantry and what recipes you can make" );
        Scanner s = new Scanner(System.in);
        int choice = s.nextInt();

        switch (choice) {
            case 1 -> pantry.show();
            case 2 -> {
              pantry.add(Ingredient.create());
              DataManager.savePantry(pantry);
            }
            case 3 -> {pantry.removal();
              DataManager.savePantry(pantry);
            }
            case 4 -> cookbook.show();
            case 5 -> cookbook.readRecipe();
            case 6 -> {cookbook.add(Recipe.create());
              DataManager.saveCookbook(cookbook);
            }
            case 7 -> {cookbook.removal();
              DataManager.saveCookbook(cookbook);
            }
            case 8 -> kitchen.comparePantryAndRecipe(pantry, cookbook);
            default -> System.out.println("Invalid choice. Please select a number from 1 to 7.");
        }
            }
          }
}
